### ISSUE TITLE
toaster popup

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#101] opened 2019-02-25 18:01 UTC
add toaster popup which fires whenever the number of datasets changes. should probably just be passed the 'visibleCollections' prop like the tooldrawer. maybe always display "# Datasets Found" and fire popup when the number changes? fire on initial load?

**Comment by JasonKleinert** [comment] 2019-02-25 19:49
This is a duplicate of #83

**Closed by JasonKleinert** 2019-02-25 19:49 UTC
Labels: enhancement, v1 TODO
